repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.8
  - repo: https://github.com/fsouza/autoflake8
    rev: v0.3.2
    hooks:
    -   id: autoflake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: flake8
  # - repo: https://github.com/pocc/pre-commit-hooks
    # rev: master
    # hooks:
      # - id: clang-format
      # - id: clang-tidy
      # - id: cppcheck
  # - repo: https://github.com/cheshirekow/cmake-format-precommit
    # rev: v0.6.10
    # hooks:
    # - id: cmake-format
    # - id: cmake-lint
